# Regions:
# Level entry:  bob_entry
# Level:        bob
# Star 2:       bob_speedrun
# Star 8:       bob_s8_log_1,bob_s8_log_2,bob_s8_log_3,bob_s8_log_4
# Cannons:      bob_cannon_1,bob_cannon_2,bob_cannon_3,bob_cannon_4,bob_cannon_5,bob_cannon_6,bob_cannon_7,bob_cannon_8,bob_cannon_9
# Warps:        bob_warp_1,bob_warp_2


variables:
  spawn:              -357.5;69;2.5;marocraft;180;12
  respawn:            -19.5;46;-431.5;marocraft;90;12
  exitsign:           -358;69;2;marocraft

events:
  init_level:         "folder init_spawns,init_warps,init_cannons,init_stars,e_play_music,init_redcoins"
  deit_level:         "folder deit_spawns,deit_warps,deit_cannons,deit_stars,e_stop_music"
  unlo_level:         "folder deit_redcoins,exit_level period:3 ticks"
  exit_level:         "folder deit_level,e_tp_respawn,core-main.init_castle"

  on_death:           "folder e_notify_death,unlo_level,e_point_add_death,e_gpoint_add_death"
  on_exit:            "folder unlo_level"

  # Wipe save
  wipe_level:         "folder wipe_stars"

  # Play music
  e_play_music:       "folder core-music.e_play_bob"
  e_stop_music:       "folder core-music.e_stop_music"

  ### --- Spawn / Respawn ---------------------------------------
  init_spawns:        "folder e_obj_add_respawn,e_obj_add_exit,e_tp_spawn"
  e_obj_add_respawn:  "objective add o_respawn"
  e_obj_add_exit:     "objective add o_exitlevel"
  deit_spawns:        "folder e_obj_del_respawn,e_obj_del_exit"
  e_obj_del_respawn:  "objective remove o_respawn"
  e_obj_del_exit:     "objective remove o_exitlevel"

  # Teleports
  e_tp_spawn:         "teleport $spawn$"
  e_tp_respawn:       "teleport $respawn$"

  # Actions
  e_notify_death:     "command broadcast &3%player%&f died in BOB."
  e_point_add_death:  "point bob_deaths 1 action:add"
  e_gpoint_add_death: "globalpoint bob_deaths 1 action:add"

  # Fake blocks
  init_redcoins:      "folder e_init_rcoins delay:1"
  deit_redcoins:      "folder e_deit_rcoins"
  e_init_rcoins:      "command showfakeskulls %player% bob_rc_1 bob_rc_2 bob_rc_3 bob_rc_4 bob_rc_5 bob_rc_6 bob_rc_7 bob_rc_8 bob_rc_9 bob_rc_10 bob_rc_11 bob_rc_12"
  e_deit_rcoins:      "command hidefakeskulls %player% bob_rc_1 bob_rc_2 bob_rc_3 bob_rc_4 bob_rc_5 bob_rc_6 bob_rc_7 bob_rc_8 bob_rc_9 bob_rc_10 bob_rc_11 bob_rc_12"


objectives:
  o_respawn:          "die cancel respawn:$respawn$ events:on_death"
  o_exitlevel:        "action right any loc:$exitsign$ events:on_exit"