

events:
  init_burn_lava:     "folder e_obj_add_blava"
  e_obj_add_blava:    "objective add o_touch_lava"


  e_fol_burn_bounce:  "folder core-sfx.e_fire_hurt,e_wait_burn,e_reload_burnlava"
  e_reload_burnlava:  "folder init_burn_lava delay:10 ticks"
  e_wait_burn:        "folder e_burn_jump delay:3 ticks"
  e_burn_jump:        "velocity vector:(0;2.5;0) direction:relative_y modification:set"


  deit_burn_lava:     "folder e_obj_del_blava"
  e_obj_del_blava:    "objective remove o_touch_lava"


objectives:
  o_touch_lava:       "region lll_main_lava enter events:e_fol_burn_bounce"