# Regions:
# Level entry:  lll_entry
# Level:        lll
# Star 8:       lll_speedrun
# Sub entry:    lll_enter_volcano
# Lavaburn:     lll_main_lava

variables:
  spawn:              -912.5;37;-406.5;marocraft;180;12
  respawn:            11.5;28;-460.5;marocraft;180;12
  exitsign:           -913;37;-407;marocraft
  # Sub area
  exitsign2:          -887;37;-655;marocraft
  inside_volcano:     -887;37;-655;marocraft;-135;12

events:
  init_level:         "folder init_spawns,init_lavaburn,init_stars,e_play_music"
  deit_level:         "folder deit_spawns,deit_lavaburn,deit_stars,e_stop_music"
  unlo_level:         "folder exit_level" # period:20 ticks
  exit_level:         "folder deit_level,e_tp_respawn,core-main.init_castle"

  on_death:           "folder e_notify_death,unlo_level,e_point_add_death,e_gpoint_add_death"
  on_exit:            "folder unlo_level"

  # Wipe save
  wipe_level:         "folder wipe_stars"

  # Play music
  e_play_music:       "folder core-music.e_play_ssl"
  e_stop_music:       "folder core-music.e_stop_music"

  ### --- Spawn / Respawn ---------------------------------------
  init_spawns:        "folder e_obj_add_respawn,e_obj_add_exit,e_obj_add_exit2,e_obj_add_tp_vol,e_tp_spawn"
  e_obj_add_respawn:  "objective add o_respawn"
  e_obj_add_exit:     "objective add o_exitlevel"
  e_obj_add_exit2:    "objective add o_exitlevel2"
  e_obj_add_tp_vol:   "objective add o_tp_volcano"

  deit_spawns:        "folder e_obj_del_respawn,e_obj_del_exit,e_obj_del_exit2,e_obj_del_tp_vol"
  e_obj_del_respawn:  "objective remove o_respawn"
  e_obj_del_exit:     "objective remove o_exitlevel"
  e_obj_del_exit2:    "objective remove o_exitlevel2"
  e_obj_del_tp_vol:   "objective remove o_tp_volcano"

  # Teleports
  e_tp_spawn:         "teleport $spawn$"
  e_tp_respawn:       "teleport $respawn$"
  # Sub area
  e_tp_volcano:       "teleport $inside_volcano$"

  # Actions
  e_notify_death:     "command broadcast &3%player%&f died in LLL."
  e_point_add_death:  "point lll_deaths 1 action:add"
  e_gpoint_add_death: "globalpoint lll_deaths 1 action:add"


objectives:
  o_respawn:          "die cancel respawn:$respawn$ events:on_death"
  o_exitlevel:        "action right any loc:$exitsign$ events:on_exit"
  # Sub area
  o_exitlevel2:       "action right any loc:$exitsign2$ events:on_exit"
  o_tp_volcano:       "region lll_enter_volcano enter events:e_tp_volcano"
