  
events:
  init_env:             "folder init_bounce,init_freezing_water,init_cold_water,init_wind"
  reset_env:            "folder cleanup_bounce,cleanup_freezing_w,cleanup_cold_water,cleanup_wind"

  
  ### Bounce pads
  init_bounce:          "folder e_obj_add_bounce_1,e_obj_add_bounce_2"
  e_obj_add_bounce_1:   "objective add o_bounce_1"
  e_obj_add_bounce_2:   "objective add o_bounce_2"

  cleanup_bounce:       "folder e_obj_del_bounce_1,e_obj_del_bounce_2"
  e_obj_del_bounce_1:   "objective remove o_bounce_1"
  e_obj_del_bounce_2:   "objective remove o_bounce_2"

  # Bounce
  e_fol_bounce:         "folder e_bounce,core-sfx.e_impact,e_reload_bounce"
  e_reload_bounce:      "folder init_bounce delay:20 ticks"
  e_bounce:             "velocity vector:(0;1;0) direction:absolute modification:set"


  ### Freezing water
  init_freezing_water:  "folder e_obj_add_freeze_w_1"
  e_obj_add_freeze_w_1: "objective add o_freeze_water_1"

  cleanup_freezing_w:   "folder e_obj_del_freeze_w_1"
  e_obj_del_freeze_w_1: "objective remove o_freeze_water_1"

  # Freeze
  e_fol_freezew:        "folder e_freeze_dmg,core-sfx.e_fire_hurt,e_freeze_jump,e_reload_freezew"
  e_reload_freezew:     "folder init_freezing_water delay:10 ticks"
  e_freeze_dmg:         "damage 4"
  e_freeze_jump:        "velocity vector:(0;0.7;0) direction:relative_y modification:set"


  ### Cold water
  init_cold_water:      "folder e_obj_add_cw_enter_1"
  e_obj_add_cw_enter_1: "objective add o_cw_enter_1"
  e_obj_add_cw_exit_1:  "objective add o_cw_exit_1"

  cleanup_cold_water:   "folder e_obj_del_cw_enter_1,e_obj_del_cw_exit_1,e_obj_del_cw_delay_1"
  e_obj_del_cw_enter_1: "objective remove o_cw_enter_1"
  e_obj_del_cw_exit_1:  "objective remove o_cw_exit_1"
  e_obj_del_cw_delay_1: "objective remove o_cw_delay_1"

  # Cold water enter
  e_fol_cw_enter:       "folder e_obj_add_cw_exit_1,e_obj_add_cw_delay_1"
  e_obj_add_cw_delay_1: "objective add o_cw_delay_1"

  # Cold water exit
  e_fol_cw_exit:        "folder e_obj_del_cw_delay_1,e_obj_add_cw_enter_1"

  # Cold water damage
  e_fol_cold_water:     "folder e_cold_water_dmg,e_obj_add_cw_delay_1"
  e_cold_water_dmg:     "damage 2"


  ### Windy ice
  init_wind:            "folder e_obj_add_windice_1,e_obj_add_windice_2,e_obj_add_windice_3,e_obj_add_windice_4,e_obj_add_windice_5"
  e_obj_add_windice_1:  "objective add o_windice_1"
  e_obj_add_windice_2:  "objective add o_windice_2"
  e_obj_add_windice_3:  "objective add o_windice_3"
  e_obj_add_windice_4:  "objective add o_windice_4"
  e_obj_add_windice_5:  "objective add o_windice_5"

  cleanup_wind:         "folder e_obj_del_windice_1,e_obj_del_windice_2,e_obj_del_windice_3,e_obj_del_windice_4,e_obj_del_windice_5"
  e_obj_del_windice_1:  "objective remove o_windice_1"
  e_obj_del_windice_2:  "objective remove o_windice_2"
  e_obj_del_windice_3:  "objective remove o_windice_3"
  e_obj_del_windice_4:  "objective remove o_windice_4"
  e_obj_del_windice_5:  "objective remove o_windice_5"


  # Wind blow
  e_fol_windyice:       "folder cleanup_wind,e_windblow,e_blow_sfx,e_reload_windice"
  e_reload_windice:     "folder init_wind delay:15 ticks"
  e_blow_sfx:           "folder core-sfx.e_wind,core-sfx.e_fall period:5 ticks"

  e_windblow:           "velocity vector:(2;0.4;2) direction:absolute modification:set"


objectives:
  # Bounce
  o_bounce_1:           "region sml_bounce_1 enter events:e_fol_bounce"
  o_bounce_2:           "region sml_bounce_2 enter events:e_fol_bounce"

  # Freezing water
  o_freeze_water_1:     "region sml_freezing_water_1 enter events:e_fol_freezew"

  # Cold water
  o_cw_enter_1:         "region sml_cold_water_1 enter events:e_fol_cw_enter"
  o_cw_exit_1:          "region sml_cold_water_1 exit events:e_fol_cw_exit"
  o_cw_delay_1:         "delay 1 seconds interval:1 events:e_fol_cold_water"

  # Wincy ice
  o_windice_1:          "region sml_windice_1 enter events:e_fol_windyice"
  o_windice_2:          "region sml_windice_2 enter events:e_fol_windyice"
  o_windice_3:          "region sml_windice_3 enter events:e_fol_windyice"
  o_windice_4:          "region sml_windice_4 enter events:e_fol_windyice"
  o_windice_5:          "region sml_windice_5 enter events:e_fol_windyice"

