# Regions:
# Level entry:      sml_entry
# Level:            sml
# Sub-level         
# Sub-level entry:  
# Cold water:       sml_col_water_1
# Freezing water:   sml_freezing_water_1
# Flower bounce:    sml_bounce_1,sml_bounce_2
# Ice wind:         sml_windice_1,sml_windice_2,sml_windice_3,sml_windice_4,sml_windice_5

variables:
  spawn:              -422.5;31;705.5;marocraft;90;12
  respawn:            60.5;67;-467.5;marocraft;180;12
  exitsign:           -423;31;705;marocraft

events:
  init_level:         "folder init_spawns,init_icewind,init_fz_water,init_cd_water,init_bounce,init_stars,e_play_music"
  deit_level:         "folder deit_spawns,deit_icewind,deit_fz_water,deit_cd_water,deit_bounce,deit_stars,e_stop_music"
  unlo_level:         "folder exit_level" # period:20 ticks
  exit_level:         "folder deit_level,e_tp_respawn,core-main.init_castle"

  on_death:           "folder e_notify_death,unlo_level,e_point_add_death,e_gpoint_add_death"
  on_exit:            "folder unlo_level"

  # Wipe save
  wipe_level:         "folder wipe_stars"

  # Play music
  e_play_music:         "folder core-music.e_play_ccm"
  e_stop_music:         "folder core-music.e_stop_music"

  ### --- Spawn / Respawn ---------------------------------------
  init_spawns:          "folder e_obj_add_respawn,e_obj_add_exit,e_tp_spawn"
  e_obj_add_respawn:    "objective add o_respawn"
  e_obj_add_exit:       "objective add o_exitlevel"
  deit_spawns:          "folder e_obj_del_respawn,e_obj_del_exit"
  e_obj_del_respawn:    "objective remove o_respawn"
  e_obj_del_exit:       "objective remove o_exitlevel"

  # Teleports
  e_tp_spawn:           "teleport $spawn$"
  e_tp_respawn:         "teleport $respawn$"

  # Actions
  e_notify_death:       "command broadcast &3%player%&f died in SML."
  e_point_add_death:    "point sml_deaths 1 action:add"
  e_gpoint_add_death:   "globalpoint sml_deaths 1 action:add"


objectives:
  o_respawn:            "die cancel respawn:$respawn$ events:on_death"
  o_exitlevel:          "action right any loc:$exitsign$ events:on_exit"
