variables:
  spawn:                396.5;46;-400.5;marocraft;180;12
  respawn:              -6;40;-152;marocraft;-45;12
  exitbtn:              396;46;-401;marocraft
  fall_warp:            418;30;-443;marocraft;135;12
  thunder_1:            408 60 -438
  thunder_2:            378 66 -433

events:
  init_level:           "folder add_level_objs,init_stars,init_env,e_tp_spawn,e_spawn_env,e_play_music"
  reload_level:         "folder reset_level,core-main.init_castle"
  reset_level:          "folder del_level_objs,reset_stars,reset_env,e_stop_music"
  hard_reset:           "folder reset_level,delete_stars"
  on_death:             "folder e_notify_death,reload_level,e_point_add_death,e_gpoint_add_death"
  on_exit:              "folder e_tp_respawn,reload_level"

  e_point_add_death:    "point bbh_deaths 1 action:add"
  e_gpoint_add_death:   "globalpoint bbh_deaths 1 action:add"

  ### Play music
  e_play_music:         "folder core-music.e_play_bbh"
  e_play_music_car:     "folder core-music.e_play_merrygo"
  e_play_music_powerup: "folder core-music.e_play_powerup"
  e_stop_music:         "folder core-music.e_stop_music"


  ### LEVEL - Add objectives
  add_level_objs:       "folder e_obj_add_respawn,e_obj_add_exit,e_obj_add_fall_1,e_obj_add_fall_2,e_obj_add_merrygo_en"
  e_obj_add_respawn:    "objective add o_respawn"
  e_obj_add_exit:       "objective add o_exitlevel"
  e_obj_add_fall_1:     "objective add o_fall_1"
  e_obj_add_fall_2:     "objective add o_fall_2"
  e_obj_add_merrygo_en: "objective add o_merrygo_enter"
  e_obj_add_merrygo_ex: "objective add o_merrygo_exit"
  ### LEVEL - Del objectives
  del_level_objs:       "folder e_obj_del_respawn,e_obj_del_exit,e_obj_del_fall_1,e_obj_del_fall_2,e_obj_del_merrygo_en,e_obj_del_merrygo_ex"
  e_obj_del_respawn:    "objective remove o_respawn"
  e_obj_del_exit:       "objective remove o_exitlevel"
  e_obj_del_fall_1:     "objective remove o_fall_1"
  e_obj_del_fall_2:     "objective remove o_fall_2"
  e_obj_del_merrygo_en: "objective remove o_merrygo_enter"
  e_obj_del_merrygo_ex: "objective remove o_merrygo_exit"

  # When spawning
  e_spawn_env:          "folder e_spawn_thunder_1,e_spawn_thunder_2,e_spawn_thunder_3,e_give_darkness period:1 delay:2"
  e_spawn_thunder_1:    "command execute in minecraft:overworld run summon lightning_bolt $thunder_1$"
  e_spawn_thunder_2:    "command execute in minecraft:overworld run summon lightning_bolt $thunder_2$"
  e_spawn_thunder_3:    "command execute in minecraft:overworld at %player% run summon lightning_bolt ~ ~ ~-3"
  e_give_darkness:      "effect DARKNESS 5 1 hidden noicon"

  # Teleports
  e_tp_spawn:           "teleport $spawn$"
  e_tp_respawn:         "teleport $respawn$"
  e_tp_fall_water:      "teleport $fall_warp$"

  # Enter merrygoround
  e_merrygo_enter:      "folder e_play_music_car,e_obj_add_merrygo_ex"
  # Exit merrygoround
  e_merrygo_exit:       "folder e_play_music,e_obj_add_merrygo_en"

  # Actions
  e_notify_death:       "command broadcast &3%player%&f died in BBH."

  # Sounds
  ### Add Sounds
  #fol_add_sounds:       "folder e_obj_add_sound_wz,e_obj_add_creepy_snd"
  # Waltz
  #e_obj_add_sound_wz:   "objective add o_sound_waltz"
  #e_obj_add_wait_wz:    "objective add o_wait_sound_waltz"
  #fol_sound_walts:      "folder e_sound_walts,e_obj_add_wait_wz"
  #e_sound_walts:        "command playsound minecraft:music_disc.mellohi music %player% $music_waltz$"
  # Creepy sounds
  #e_obj_add_creepy_snd: "objective add o_wait_creepy"
  #e_obj_del_creepy_snd: "objective remove o_wait_creepy"
  #e_play_creepy_1:      "if chk_creepy_1 e_sound_creepy_1 else e_play_creepy_2"
  #e_play_creepy_2:      "if chk_creepy_2 e_sound_creepy_2 else e_play_creepy_3"
  #e_play_creepy_3:      "if chk_creepy_3 e_sound_creepy_3 else e_sound_creepy_4"
  #e_sound_creepy_1:     "command playsound minecraft:entity.ghast.death music %player% %location.xyz% 50 0.5"
  #e_sound_creepy_2:     "command playsound minecraft:entity.allay.death music %player% %location.xyz% 50 0.5"
  #e_sound_creepy_3:     "command playsound minecraft:entity.zombie_horse.death music %player% %location.xyz% 50 0.5"
  #e_sound_creepy_4:     "command playsound minecraft:entity.piglin.angry music %player% %location.xyz% 50 0.5"

  ### Del Sounds
  #fol_del_sounds:       "folder e_obj_del_sound_wz,e_obj_del_wait_wz,e_obj_del_creepy_snd"
  # Waltz
  #e_obj_del_sound_wz:   "objective remove o_sound_waltz"
  #e_obj_del_wait_wz:    "objective remove o_wait_sound_waltz"
  

  ### Add effects
  #e_add_effects:        "folder e_fol_darkness,e_fol_invis"
  # Blindness
  #e_fol_darkness:       "folder effect_darkness,start_darkness"
  #start_darkness:       "objective add o_wait_darkness"
  #effect_darkness:      "effect DARKNESS 10 1 hidden noicon"
  # Invisibility
  #e_fol_invis:          "folder start_invis"
  #start_invis:          "objective add o_wait_invis"
  #effect_invis:         "effect INVISIBILITY 10 1 hidden noicon"
  
  ### Del effects
  #e_del_effects:        "folder e_fol_del_darkness,e_fol_del_invis"
  # Blindness
  #e_fol_del_darkness:   "folder end_darkness,uneffect_darkness"
  #end_darkness:         "objective remove o_wait_darkness"
  #uneffect_darkness:    "command effect clear %player%"
  # Invisibility
  #e_fol_del_invis:      "folder end_invis,uneffect_invis"
  #end_invis:            "objective remove o_wait_invis"
  #uneffect_invis:       "command effect clear %player%"


objectives:
  o_respawn:            "die cancel respawn:$respawn$ events:on_death"
  o_exitlevel:          "action right any loc:$exitbtn$ events:on_exit"
  o_fall_1:             "region bbh_fall_1 enter events:e_tp_fall_water persistent"
  o_fall_2:             "region bbh_fall_2 enter events:e_tp_fall_water persistent"

  o_merrygo_enter:      "region bbh_merrygo enter events:e_merrygo_enter"
  o_merrygo_exit:       "region bbh_merrygo exit events:e_merrygo_exit"
  
  #o_sound_waltz:        "region bbh_waltz2 enter events:fol_sound_walts"
  #o_wait_sound_waltz:   "delay 96 seconds interval:100 events:e_obj_add_sound_wz"

  #o_wait_darkness:      "delay %randomnumber.whole.30~120% seconds interval:100 events:e_fol_darkness"
  #o_wait_invis:         "delay %randomnumber.whole.30~120% seconds interval:100 events:e_fol_invis"

  #o_wait_creepy:        "delay %randomnumber.whole.100~200% seconds interval:100 events:e_play_creepy_1 persistent"

conditions:
  #chk_creepy_1:         "random 1-4"
  #chk_creepy_2:         "random 1-3"
  #chk_creepy_3:         "random 1-2"