events:
  init_main:        "folder core-castle.init_castle,init_abilities,core-commands.init_commands"
  deit_main:        "folder core-castle.deit_castle,deit_abilities,core-commands.deit_commands"


  e_dummy:          "tag add dummy"



  # [tmp] Secret slide 2 unlock
  e_unlock_ss2:                 "if !chk_ss2_unlocked e_fol_unlock_ss2 else e_dummy"
  e_fol_unlock_ss2:             "folder e_tag_add_unlock_ss2,e_notify_unlock_ss2"
  e_notify_unlock_ss2:          "notify Secret Slide #2 has now been unlocked!"
  e_tag_add_unlock_ss2:         "tag add ss2_unlock"
  e_tag_del_unlock_ss2:         "tag delete ss2_unlock"

conditions:
  chk_ss2_unlocked:             "tag ss2_unlock"
